#!/bin/sh

# Run Rector - показывает что изменит и отдает ответ "exit 1"
# Run Laravel Pint - исправляет стиль кода и отдает ответ "exit 1"
# Run PhpStan - показывает ошибки в коде и отдает ответ "exit 1"

# Каждая команда возвращает "exit 1" и по команде commit не будут зафиксированы изменения
# Команды можно выполнить `composer fix`

./vendor/bin/rector process --clear-cache --dry-run && ./vendor/bin/pint --repair && ./vendor/bin/phpstan analyse
